### ISSUE TITLE
Mvn command equivalent

### ISSUE THREAD

**Issue by alexjoybc** [quarkusio/code.quarkus.io#401] opened 2020-10-19 20:14 UTC
**Description**

When doing the selection of the configuration for the Quarkus startup project, it would be nice to be able to get the equivalent command in maven

**Comment by maxandersen** [comment] 2021-01-03 07:33
Valid request - reopening

**Comment by ia3andy** [comment] 2021-10-05 14:28
Duplicate of #186

**Closed by ia3andy** 2021-10-05 14:28 UTC
Labels: feature, pinned
