### ISSUE TITLE
Missing extensions is missing some info

### ISSUE THREAD

**Issue by mmuzikar** [quarkusio/code.quarkus.io#756] opened 2022-02-01 13:01 UTC
**Describe the bug**
When adding an invalid extension to the URL there's a warning pop-up that's missing some key info.

**Expected behavior**
I'd expect when navigating to https://code.quarkus.io?e=my-extension to be displayed with message `<my-extension> is missing from the current stream '<stream-name>', it has been unselected.`

**Actual behavior**
But the warning looks like this 
![image](https://user-images.githubusercontent.com/46345469/151972953-ea710215-f37e-4f7d-b45d-ae6934869a32.png)

**To Reproduce**
1. Navigate to https://code.quarkus.io?e=my-extension 
2. 
3. 

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser: Firefox and Chromium both have the issue
 - OS: Fedora 32

**Additional context**
(Add any other context about the problem here.)

**Comment by ia3andy** [comment] 2022-02-07 09:13
Thanks for reporting.

Duplicate of https://github.com/quarkusio/code.quarkus.io/issues/547

**Closed by ia3andy** 2022-02-07 09:13 UTC
Labels: bug
