### ISSUE TITLE
Add some filter shortcuts like "preview", "provides-example", ...

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/code.quarkus.io#395] opened 2020-09-25 14:40 UTC
**Description**
It would be nice if we could filter the extensions by showing only those containing example codes

**Comment by ia3andy** [comment] 2020-09-25 14:48
I was thinking about some kind of autocompletion and suggestions, when you focus, you see suggestions, then you get better suggestions as you are typing..

**Comment by ia3andy** [comment] 2021-10-05 14:26
duplicate of #459

**Closed by ia3andy** 2021-10-05 14:26 UTC
Labels: feature, pinned
